#ifndef STYLE_H
#define STYLE_H

static const char *APP_CSS =
    "#main-window {"
    "  background-color: #000000;"
    "}"
    "window {"
    "  background-color: #000000;"
    "}"

    ".clock-time {"
    "  font-size: 240px;"
    "  font-weight: bold;"
    "  color: #ffffff;"
    "  letter-spacing: -4px;"
    "}"
    ".clock-date {"
    "  font-size: 48px;"
    "  color: #cccccc;"
    "  margin-top: 0px;"
    "}"

    ".weather-section {"
    "  background-color: rgba(20, 20, 20, 0.85);"
    "  border-radius: 12px;"
    "  padding: 8px 12px;"
    "}"
    ".weather-title {"
    "  font-size: 20px;"
    "  font-weight: bold;"
    "  color: #ffffff;"
    "  margin-bottom: 6px;"
    "}"
    ".weather-container {"
    "  padding: 4px;"
    "}"
    ".weather-hour {"
    "  background-color: rgba(50, 50, 50, 0.8);"
    "  border-radius: 8px;"
    "  padding: 8px 12px;"
    "  margin: 3px;"
    "  min-width: 80px;"
    "}"
    ".weather-time {"
    "  font-size: 22px;"
    "  font-weight: bold;"
    "  color: #ffffff;"
    "}"
    ".weather-icon {"
    "  font-size: 32px;"
    "  margin: 4px 0;"
    "}"
    ".weather-temp {"
    "  font-size: 42px;"
    "  font-weight: bold;"
    "  color: #ffffff;"
    "}"
    ".weather-desc {"
    "  font-size: 15px;"
    "  color: #aaaaaa;"
    "}"

    ".error-text {"
    "  color: #ff6b6b;"
    "  font-size: 14px;"
    "  padding: 10px;"
    "}"

    ".location-box {"
    "  padding: 8px;"
    "  margin-bottom: 8px;"
    "}"
    ".location-box label {"
    "  margin: 0 4px;"
    "  color: #ffffff;"
    "  font-size: 14px;"
    "}"
    ".location-box entry {"
    "  min-width: 90px;"
    "  margin: 0 8px;"
    "  padding: 4px 8px;"
    "  background-color: #1a1a1a;"
    "  color: #ffffff;"
    "}"

    ".exit-button {"
    "  padding: 6px 14px;"
    "  font-size: 13px;"
    "  background-color: #bf616a;"
    "  color: #000000;"
    "  border-radius: 4px;"
    "}"
    ".exit-button:hover {"
    "  background-color: #a04850;"
    "}"

    ".settings-title {"
    "  font-size: 20px;"
    "  font-weight: bold;"
    "  color: #ffffff;"
    "  margin-bottom: 12px;"
    "}";

#endif
